name: project_athens
description: A new Flutter application.
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_crashlytics: ^0.1.4+1
  firebase_messaging: ^6.0.16
  provider: ^4.3.1
  fluro: ^1.6.3
  floor: ^0.14.0
  sqflite: ^1.3.1
  flutter_fimber: ^0.4.4
  flutter_vlc_player: ^3.0.5
  chopper: ^3.0.3
  rxdart: ^0.24.1
  modal_bottom_sheet: ^0.2.0+1
  percent_indicator: ^2.1.5
  material_design_icons_flutter: ^4.0.5345
  intl: ^0.16.1
  json_annotation: ^3.0.1
  flutter_secure_storage: ^3.3.3
  email_validator: ^1.0.5
  lang_generator:
    path: lang_generator

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.14.0
  build_runner: ^1.10.0
  chopper_generator: ^3.0.5
  json_serializable: ^3.3.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - resources/lang/

    - resources/images/
