name: project_athens
description: A new Flutter application.
version: 0.0.4+3

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: 0.5.2
  firebase_crashlytics: ^0.2.1
  firebase_messaging: ^7.0.2
  provider: ^4.3.2+2
  floor: ^0.14.0
  sqflite: ^1.3.1+1
  flutter_fimber: ^0.4.4
  flutter_vlc_player: ^4.0.1
  dio: 3.0.10
  dio_firebase_performance: 0.2.0
  retrofit: ^1.3.4+1
  logger: ^0.9.4
  rxdart: ^0.24.1
  modal_bottom_sheet: ^0.2.2
  percent_indicator: ^2.1.7+4
  material_design_icons_flutter: ^4.0.5755
  intl: ^0.16.1
  json_annotation: ^3.1.0
  flutter_secure_storage: ^3.3.4
  email_validator: ^1.0.5
  flutter_scatter: ^0.1.0
  video_player: ^0.10.12+3
  flick_video_player: ^0.1.1
  sortedmap: ^0.4.2+1
  syncfusion_flutter_datepicker: ^18.4.39-beta
  lang_generator:
    path: lang_generator

  # fix for ios build
  # error: /Users/runner/work/project_athens_mobile/project_athens_mobile/ios/Flutter/Release.xcconfig:1:
  # could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig' in search paths (in target 'Runner' from project 'Runner')
  path_provider: 1.6.18

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.14.0
  build_runner: ^1.10.0
  retrofit_generator: ^1.3.4+1
  json_serializable: ^3.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - resources/lang/

    - resources/images/
