name: project_athens
description: Świadoma Demokoracja to aplikacja to śledzenia aktywności poselskiej w sejmie.
version: 1.0.0-beta.1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.0
  firebase_messaging: ^11.2.6
  provider: ^6.0.2
  drift: ^1.4.0
  sqlite3_flutter_libs: ^0.5.3
  path: ^1.8.0
  flutter_fimber: ^0.6.5
  dio: ^4.0.4
#  dio_firebase_performance: 0.2.0
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  rxdart: ^0.27.3
  modal_bottom_sheet: ^2.0.0
  percent_indicator: ^4.0.0
  material_design_icons_flutter: ^5.0.6595
  intl: ^0.17.0
  json_annotation: ^4.4.0
  flutter_secure_storage: ^5.0.2
  email_validator: ^2.0.1
  flutter_scatter: ^0.2.0
  video_player: ^2.2.17
  flutter_vlc_player: ^7.0.1
  sortedmap: ^0.5.1
  syncfusion_flutter_datepicker: ^19.4.50
  cached_network_image: 3.2.0
  circular_countdown_timer: ^0.2.0
  google_mobile_ads: ^1.0.1
  uuid: ^3.0.5
  lang_generator:
    path: lang_generator

  # fix for ios build
  # error: /Users/runner/work/project_athens_mobile/project_athens_mobile/ios/Flutter/Release.xcconfig:1:
  # could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig' in search paths (in target 'Runner' from project 'Runner')
  path_provider: 2.0.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  wakelock: ^0.6.1+1
  url_launcher: ^6.0.18
  in_app_update: ^2.0.0
  package_info: 2.0.2
  upgrader: ^3.13.0
  reorderableitemsview: ^2.0.1
  charts_flutter: ^0.12.0
  fijkplayer: ^0.10.1
  fijkplayer_skin:
    git:
      url: https://github.com/pbrejdak/fijkplayer_skin.git
      ref: main
  version: ^2.0.0
  badges: ^2.0.2
  table_calendar: ^3.0.3
  flutter_widget_from_html_core: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_launcher_icons: 0.9.2
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.4
  drift_dev: ^1.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter_icons:
  ios: true
  image_path_android: "icon_launcher/ios.png"
  adaptive_icon_foreground: "icon_launcher/android.png"
  adaptive_icon_background: "icon_launcher/ic_launcher_background.png"
  image_path_ios: "icon_launcher/ios.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - resources/lang/

    - resources/images/
    - resources/images/parliament/
