name: splash_screen
description: A new Flutter package.
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.5
  chopper: ^3.0.2
  rxdart: ^0.24.0
  athens_core:
    path: ../athens_core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
