enum DashboardTiles {
  NAME,
  NOTIFICATIONS,
  SETTINGS_BUTTON,
  NEAREST_MEETING,
  DEPUTIES,
  SPEECHES,
  VOTES,
  CHART_VOTES_ABSENT,
  CHART_VOTES_ABSENT_PER_YEAR,
  CHART_SPEECHES_COUNTER,
  CHART_SPEECHES_COUNTER_PER_YEAR,
}