name: athens_core
description: A new Flutter package.
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  chopper: ^3.0.2
  json_annotation: ^3.0.1
  lang_generator:
    path: ../lang_generator
  pagination:
    path: ../pagination

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  chopper_generator: ^3.0.4
  json_serializable: ^3.3.0

flutter:

  assets:
    - ../resources/lang/

    - ../resources/images/
