name: lang_generator
description: Classes thats generates code for project NLH
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.5

dev_dependencies:
  build_test: ^1.2.0
  build_runner: ^1.10.0
  test: ^1.15.1

