name: lang_generator
description: Classes thats generates code for project NLH
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  build: ^2.0.1
  source_gen: ^1.0.1

dev_dependencies:
  build_test: ^2.1.2
  build_runner: ^2.0.6
  test: ^1.15.1

