name: timeline_flow
description: A new Flutter package.
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.5
  floor: ^0.12.0
  fluro: ^1.6.3
  chopper: ^3.0.2
  json_annotation: ^3.0.1
  flutter_secure_storage: ^3.3.2
  rxdart: ^0.24.0
  material_design_icons_flutter: 4.0.5245
  intl: ^0.16.1
  athens_core:
    path: ../athens_core
  pagination:
    path: ../pagination

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  chopper_generator: ^3.0.4
  json_serializable: ^3.3.0

flutter:

